"""Declarative base, shared column types and the common model mixin."""
from decimal import Decimal, ROUND_HALF_UP
from typing import Any, Optional

from sqlalchemy import Column, DateTime, Integer, Numeric
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import declarative_base
from sqlalchemy.types import TypeDecorator

from src.core.time_utils import utc_now

Base = declarative_base()

MONEY_PRECISION = 18
MONEY_SCALE = 4
_QUANTUM = Decimal(1).scaleb(-MONEY_SCALE)


class Money(TypeDecorator):
    """A portable fixed-point money column.

    Stored as NUMERIC(18,4) on every backend, and always handed back to Python
    as a ``Decimal`` quantised to 4 dp. On SQLite we ask the dialect for the
    non-decimal variant (SQLite has no native decimal type, and letting
    SQLAlchemy do the conversion emits a warning on every read) and do the
    Decimal conversion ourselves. SQL-side ``SUM``/``AVG`` still work on both
    backends, which the P&L reports rely on.
    """

    impl = Numeric(MONEY_PRECISION, MONEY_SCALE)
    cache_ok = True

    def load_dialect_impl(self, dialect: Any) -> Any:
        if dialect.name == "sqlite":
            return dialect.type_descriptor(
                Numeric(MONEY_PRECISION, MONEY_SCALE, asdecimal=False)
            )
        return dialect.type_descriptor(Numeric(MONEY_PRECISION, MONEY_SCALE))

    def process_bind_param(self, value: Any, dialect: Any) -> Any:
        if value is None:
            return None
        quantised = Decimal(str(value)).quantize(_QUANTUM, rounding=ROUND_HALF_UP)
        return float(quantised) if dialect.name == "sqlite" else quantised

    def process_result_value(self, value: Any, dialect: Any) -> Optional[Decimal]:
        if value is None:
            return None
        return Decimal(str(value)).quantize(_QUANTUM, rounding=ROUND_HALF_UP)


# Millisecond-or-better timestamps. Plain MySQL DATETIME truncates to whole
# seconds, which would silently destroy the order-history requirement, so the
# MySQL variant is pinned to fractional-second precision 6. SQLite stores
# ISO-8601 strings and keeps microseconds as written.
#
# timezone=False throughout: values are naive UTC (see src.core.time_utils).
PreciseDateTime = DateTime(timezone=False).with_variant(mysql.DATETIME(fsp=6), "mysql")


class TimestampedModel(Base):
    """Common id + audit columns.

    This is a single-user tool, so there is no tenant or owner column.
    """

    __abstract__ = True

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    # Python-side defaults rather than server defaults: MySQL only accepts
    # CURRENT_TIMESTAMP defaults on DATETIME from 8.0.13 in the DEFAULT (expr)
    # form, and the autogenerated SQLite spelling is not valid MySQL at all.
    # Setting them in Python keeps one migration script working on both.
    created_at = Column(
        PreciseDateTime, default=utc_now, nullable=False, index=True
    )
    updated_at = Column(
        PreciseDateTime, default=utc_now, onupdate=utc_now, nullable=False
    )

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(id={self.id})>"
