"""charges breakdown becomes component driven

`order_charges` had a column per tax: ctt, exchange_transaction_charge,
sebi_turnover_fee, stamp_duty, gst, brokerage. Which taxes exist is a property
of the RATE CARD an order was charged under -- MCX commodity options pay CTT,
an NSE equity strategy would pay STT on a different transaction -- so a column
per tax means a schema migration every time a card gains a line item.

The line items now live in `breakdown_json`, which already held them.
`turnover`, `total_charges` and `rates_version` stay real columns because they
are queried and aggregated.

DATA MIGRATION. `breakdown_json` previously stored each component's UNROUNDED
amount while the dropped columns held the rounded ones, so simply dropping the
columns would have shifted every reported component total by fractions of a
paisa. Upgrade therefore rewrites each row's breakdown from the columns about
to disappear: the column value becomes the component's `amount`, and the
existing unrounded figure is preserved as `rawAmount`. No total moves.

Downgrade recreates the columns and refills them from the breakdown, so a
rollback is not a data loss either.

Revision ID: 07984c863dd3
Revises: 7bc6db18f698
Create Date: 2026-09-18 01:23:13.259114

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401


revision: str = '07984c863dd3'
down_revision: Union[str, None] = '7bc6db18f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The columns being folded into the breakdown, and the label each line item
# gets so an existing order still reads the way it did in the UI.
FOLDED_COLUMNS = (
    ("brokerage", "Brokerage"),
    ("ctt", "CTT"),
    ("exchange_transaction_charge", "Exchange transaction charge"),
    ("sebi_turnover_fee", "SEBI turnover fee"),
    ("stamp_duty", "Stamp duty"),
    ("gst", "GST"),
)


def _existing_raw_amounts(breakdown_json) -> dict:
    """{name: rawAmount} from the pre-migration breakdown, if it parses."""
    if not breakdown_json:
        return {}
    try:
        rows = json.loads(breakdown_json)
    except (TypeError, ValueError):
        return {}
    if not isinstance(rows, list):
        return {}
    return {
        str(row.get("name")): row.get("amount")
        for row in rows
        if isinstance(row, dict) and row.get("name")
    }


def upgrade() -> None:
    connection = op.get_bind()
    columns = ", ".join(name for name, _label in FOLDED_COLUMNS)
    rows = connection.execute(
        sa.text(f"SELECT id, breakdown_json, {columns} FROM order_charges")
    ).fetchall()

    for row in rows:
        mapping = row._mapping
        raw = _existing_raw_amounts(mapping["breakdown_json"])
        components = []
        for name, label in FOLDED_COLUMNS:
            amount = mapping[name]
            components.append(
                {
                    "name": name,
                    "label": label,
                    # The ROUNDED figure that was in the column: this is what
                    # every total already reflects.
                    "amount": str(amount if amount is not None else "0"),
                    "rawAmount": (
                        str(raw[name]) if name in raw and raw[name] is not None else None
                    ),
                    "rate": None,
                    "base": None,
                    "formula": "",
                    "note": "",
                }
            )
        connection.execute(
            sa.text(
                "UPDATE order_charges SET breakdown_json = :breakdown WHERE id = :id"
            ).bindparams(breakdown=json.dumps(components), id=mapping["id"])
        )

    with op.batch_alter_table('order_charges', schema=None) as batch_op:
        batch_op.drop_column('sebi_turnover_fee')
        batch_op.drop_column('ctt')
        batch_op.drop_column('exchange_transaction_charge')
        batch_op.drop_column('gst')
        batch_op.drop_column('brokerage')
        batch_op.drop_column('stamp_duty')


def downgrade() -> None:
    # Added nullable, refilled from the breakdown, and only then made NOT NULL
    # -- the same order the forward migrations use, for the same reason.
    with op.batch_alter_table('order_charges', schema=None) as batch_op:
        for name, _label in FOLDED_COLUMNS:
            batch_op.add_column(
                sa.Column(name, sa.NUMERIC(precision=18, scale=4), nullable=True)
            )

    connection = op.get_bind()
    rows = connection.execute(
        sa.text("SELECT id, breakdown_json FROM order_charges")
    ).fetchall()
    for row in rows:
        amounts = _existing_raw_amounts(row._mapping["breakdown_json"])
        assignments = ", ".join(f"{name} = :{name}" for name, _label in FOLDED_COLUMNS)
        params = {
            name: str(amounts.get(name) or "0") for name, _label in FOLDED_COLUMNS
        }
        params["id"] = row._mapping["id"]
        connection.execute(
            sa.text(
                f"UPDATE order_charges SET {assignments} WHERE id = :id"
            ).bindparams(**params)
        )

    with op.batch_alter_table('order_charges', schema=None) as batch_op:
        for name, _label in FOLDED_COLUMNS:
            batch_op.alter_column(
                name,
                existing_type=sa.NUMERIC(precision=18, scale=4),
                nullable=False,
            )
