"""add feature toggles for strategies and capabilities

Which strategies and capabilities are RUNNING is runtime state, so it lives in
the database rather than in conf/strategies/*.yaml. The YAML says what a
strategy IS -- its underlying, its contract specs, its rate card, its margin
model -- and none of that is editable from the UI. Whether it is on is, and
that is this table.

No rows are seeded. An absent row means "use the default the YAML declares"
(`enabled_by_default`, and `capabilities.*.enabled` in default-config.yaml), so
a fresh installation behaves exactly as it did before this table existed, and
an operator who has never opened the Strategies page has no rows at all.

Revision ID: 2966a4a8ed93
Revises: f613abaeee0f
Create Date: 2026-09-18 02:08:42.818564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = '2966a4a8ed93'
down_revision: Union[str, None] = 'f613abaeee0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_toggles',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('toggle_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'toggle_key', name='uq_feature_toggle')
    )
    with op.batch_alter_table('feature_toggles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_toggles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_toggles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_toggles_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_toggles_toggle_key'), ['toggle_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_toggles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_toggles_toggle_key'))
        batch_op.drop_index(batch_op.f('ix_feature_toggles_scope'))
        batch_op.drop_index(batch_op.f('ix_feature_toggles_id'))
        batch_op.drop_index(batch_op.f('ix_feature_toggles_created_at'))

    op.drop_table('feature_toggles')
    # ### end Alembic commands ###
