"""add strategy_key to trade data

Every order, position and chart trade now says which strategy module it belongs
to. The alternative -- deriving it at read time from
`instruments.underlying_symbol` -- was considered and rejected: instrument rows
are upserted and deactivated as expiries roll, so a historical order would lose
its join the moment its contract expired and would then vanish from every
filtered view, taking its P&L with it.

Existing rows are backfilled to the configured strategy. There is exactly one
(`mcx-crude-options`), and every row in this database was placed against it.
The column is added nullable, backfilled, and only then made NOT NULL, so no
row is ever left pointing at nothing.

Revision ID: 7bc6db18f698
Revises: 87f9af0f1435
Create Date: 2026-09-18 01:01:17.745462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401


revision: str = '7bc6db18f698'
down_revision: Union[str, None] = '87f9af0f1435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The key every pre-existing row is backfilled to. Read from the configured
# strategy modules where possible so a renamed module still lands on itself;
# the literal is the fallback for an environment whose config is not loadable
# at migration time, and is the name this repository has always used.
FALLBACK_STRATEGY_KEY = "mcx-crude-options"

TABLES = ("orders", "positions", "chart_trades")


def _backfill_key() -> str:
    try:
        from src.strategies.services.strategy_registry import get_strategy_registry

        return get_strategy_registry().default().key
    except Exception:  # noqa: BLE001 - a migration must not depend on app config
        return FALLBACK_STRATEGY_KEY


def upgrade() -> None:
    strategy_key = _backfill_key()

    # 1. Add nullable so existing rows survive the ALTER.
    for table in TABLES:
        op.add_column(table, sa.Column("strategy_key", sa.String(length=64), nullable=True))

    # 2. Backfill. A null here would mean a trade belonging to no strategy,
    #    which disappears from every filtered view.
    for table in TABLES:
        op.execute(
            sa.text(f"UPDATE {table} SET strategy_key = :key").bindparams(
                key=strategy_key
            )
        )

    # 3. Only now is NOT NULL safe.
    for table in TABLES:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.alter_column(
                "strategy_key",
                existing_type=sa.String(length=64),
                nullable=False,
            )

    with op.batch_alter_table('chart_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_trades_strategy_key'), ['strategy_key'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_strategy_key'), ['strategy_key'], unique=False)
        batch_op.create_index('ix_orders_strategy_placed', ['strategy_key', 'placed_at'], unique=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_strategy_key'), ['strategy_key'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_strategy_key'))
        batch_op.drop_column('strategy_key')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_strategy_placed')
        batch_op.drop_index(batch_op.f('ix_orders_strategy_key'))
        batch_op.drop_column('strategy_key')

    with op.batch_alter_table('chart_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_trades_strategy_key'))
        batch_op.drop_column('strategy_key')
