"""add chart_trades for one-click chart trading

Revision ID: 87f9af0f1435
Revises: 8f6c9e03d9ef
Create Date: 2026-09-17 00:44:38.689548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = '87f9af0f1435'
down_revision: Union[str, None] = '8f6c9e03d9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_trades',
    sa.Column('underlying_security_id', sa.String(length=32), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=128), nullable=False),
    sa.Column('option_security_id', sa.String(length=32), nullable=False),
    sa.Column('option_symbol', sa.String(length=128), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('strike_price', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('chart_side', sa.String(length=8), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=True),
    sa.Column('exit_order_id', sa.Integer(), nullable=True),
    sa.Column('stop_loss_level', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('take_profit_level', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exit_reason', sa.String(length=16), nullable=True),
    sa.Column('triggered_level', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('underlying_at_entry', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('underlying_at_exit', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('opened_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('closed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chart_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_trades_entry_order_id'), ['entry_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_trades_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_trades_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_trades_option_security_id'), ['option_security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_trades_underlying_security_id'), ['underlying_security_id'], unique=False)
        batch_op.create_index('ix_chart_trades_underlying_status', ['underlying_security_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_trades_underlying_status')
        batch_op.drop_index(batch_op.f('ix_chart_trades_underlying_security_id'))
        batch_op.drop_index(batch_op.f('ix_chart_trades_status'))
        batch_op.drop_index(batch_op.f('ix_chart_trades_option_security_id'))
        batch_op.drop_index(batch_op.f('ix_chart_trades_id'))
        batch_op.drop_index(batch_op.f('ix_chart_trades_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_chart_trades_entry_order_id'))
        batch_op.drop_index(batch_op.f('ix_chart_trades_created_at'))

    op.drop_table('chart_trades')
    # ### end Alembic commands ###
