"""Add the IPO dashboard tables

Four tables for /ipo, which is NOT a strategy: it places no orders, touches no
portfolio and reads no feed. Additive only -- nothing existing is altered, so
every strategy is untouched by this.

* `ipos` -- one durable row per mainboard IPO, keyed on the source's own id.
  Never deleted: an IPO that drops off the source page after listing has to
  stay, which is the whole reason for storing rather than proxying.
* `ipo_gmp_readings` -- a TIME SERIES, one row per capture, so how GMP moved
  before a listing is answerable. Fetched data, not accumulated ticks (root
  CLAUDE.md section 4).
* `ipo_actions` -- APPEND-ONLY. Applied / mandate accepted / rejected, each
  with its timestamp and the user who set it, because "when did I accept that
  mandate" is a question about history that a mutable boolean cannot answer.
* `ipo_job_runs` -- when a scheduled job ran, keyed on the SLOT. The durable
  half of the once-per-slot guard; the unique constraint is what stops a
  restart at 14:20 re-sending the 14:00 reminder.

SME issues are filtered out before anything is written, and an IPO first
observed already listed is not stored at all -- the Listed tab is forward-only
and there is no backfill.

Verified against SQLite. MySQL is DDL-compile-verified only, like every other
migration here.

Revision ID: 8a20ed251575
Revises: eeea383182b8
Create Date: 2026-09-19 23:27:37.500667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = '8a20ed251575'
down_revision: Union[str, None] = 'eeea383182b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipo_job_runs',
    sa.Column('job_kind', sa.String(length=32), nullable=False),
    sa.Column('slot_key', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_kind', 'slot_key', name='uq_ipo_job_runs_kind_slot')
    )
    with op.batch_alter_table('ipo_job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipo_job_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_job_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_job_runs_job_kind'), ['job_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_job_runs_slot_key'), ['slot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_job_runs_started_at'), ['started_at'], unique=False)

    op.create_table('ipos',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('issue_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('issue_price_text', sa.String(length=64), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('listing_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('first_seen_status', sa.String(length=16), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipos_close_date'), ['close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipos_listing_date'), ['listing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipos_source_id'), ['source_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ipos_status'), ['status'], unique=False)

    op.create_table('ipo_actions',
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('acted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ipo_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipo_actions_acted_at'), ['acted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_actions_id'), ['id'], unique=False)
        batch_op.create_index('ix_ipo_actions_ipo_action_acted', ['ipo_id', 'action', 'acted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_actions_ipo_id'), ['ipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_actions_user_id'), ['user_id'], unique=False)

    op.create_table('ipo_gmp_readings',
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('gmp', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('gmp_percent', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ipo_gmp_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipo_gmp_readings_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_gmp_readings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_gmp_readings_id'), ['id'], unique=False)
        batch_op.create_index('ix_ipo_gmp_readings_ipo_captured', ['ipo_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ipo_gmp_readings_ipo_id'), ['ipo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipo_gmp_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipo_gmp_readings_ipo_id'))
        batch_op.drop_index('ix_ipo_gmp_readings_ipo_captured')
        batch_op.drop_index(batch_op.f('ix_ipo_gmp_readings_id'))
        batch_op.drop_index(batch_op.f('ix_ipo_gmp_readings_created_at'))
        batch_op.drop_index(batch_op.f('ix_ipo_gmp_readings_captured_at'))

    op.drop_table('ipo_gmp_readings')
    with op.batch_alter_table('ipo_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipo_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ipo_actions_ipo_id'))
        batch_op.drop_index('ix_ipo_actions_ipo_action_acted')
        batch_op.drop_index(batch_op.f('ix_ipo_actions_id'))
        batch_op.drop_index(batch_op.f('ix_ipo_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_ipo_actions_action'))
        batch_op.drop_index(batch_op.f('ix_ipo_actions_acted_at'))

    op.drop_table('ipo_actions')
    with op.batch_alter_table('ipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipos_status'))
        batch_op.drop_index(batch_op.f('ix_ipos_source_id'))
        batch_op.drop_index(batch_op.f('ix_ipos_listing_date'))
        batch_op.drop_index(batch_op.f('ix_ipos_id'))
        batch_op.drop_index(batch_op.f('ix_ipos_created_at'))
        batch_op.drop_index(batch_op.f('ix_ipos_close_date'))

    op.drop_table('ipos')
    with op.batch_alter_table('ipo_job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipo_job_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_ipo_job_runs_slot_key'))
        batch_op.drop_index(batch_op.f('ix_ipo_job_runs_job_kind'))
        batch_op.drop_index(batch_op.f('ix_ipo_job_runs_id'))
        batch_op.drop_index(batch_op.f('ix_ipo_job_runs_created_at'))

    op.drop_table('ipo_job_runs')
    # ### end Alembic commands ###
