"""add users table with roles

Replaces the single hardcoded APP_USERNAME / APP_PASSWORD credential pair with
a real users table, two roles and a per-account status.

The default administrator (trader@abc.com) is seeded here so a freshly migrated
database is usable immediately. Its password comes from APP_ADMIN_PASSWORD --
never a literal in source. If that is not set the row is skipped with a loud
log line rather than being created with a guessable password; the application
seeds it on the next start once the variable is present.

Revision ID: 8f6c9e03d9ef
Revises: 8926d5407581
Create Date: 2026-09-16 23:04:37.833420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

from src import config_utils
from src.constants import UserRole, UserStatus
from src.core.time_utils import utc_now
from src.logging_config import get_logger
from src.users.services import password_service
from src.users.services.user_service import (
    SEED_USER_EMAIL,
    SEED_USER_FIRST_NAME,
    SEED_USER_LAST_NAME,
)

logger = get_logger("database.migrations")

revision: str = '8f6c9e03d9ef'
down_revision: Union[str, None] = '8926d5407581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_seed_user', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('password_changed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_seed_user'), ['is_seed_user'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###

    _seed_default_administrator()


def _seed_default_administrator() -> None:
    """Insert the default administrator so the database is usable on arrival.

    `must_change_password` is deliberately False: the default credential is
    allowed to stand for this local single-user tool. That is a known, recorded
    risk (see the README's "Known gaps"), not an oversight.

    Written with op.bulk_insert against a lightweight table definition rather
    than the ORM model, so this migration keeps working if the model later
    gains or loses a column.
    """
    admin_password = config_utils.get_property_value("auth.admin_password", "")
    if not admin_password:
        logger.error(
            "APP_ADMIN_PASSWORD is not set, so the default administrator (%s) "
            "was NOT created and nobody can log in yet. Set it in .env; the "
            "application seeds the account on its next start.",
            SEED_USER_EMAIL,
        )
        return

    try:
        password_hash = password_service.hash_password(admin_password)
    except password_service.PasswordError as exc:
        logger.error(
            "APP_ADMIN_PASSWORD is unusable (%s), so the default administrator "
            "was NOT created. Fix it and restart; the application seeds the "
            "account on its next start.",
            exc,
        )
        return

    users = sa.table(
        "users",
        sa.column("email", sa.String),
        sa.column("first_name", sa.String),
        sa.column("last_name", sa.String),
        sa.column("password_hash", sa.String),
        sa.column("role", sa.String),
        sa.column("status", sa.String),
        sa.column("must_change_password", sa.Boolean),
        sa.column("is_seed_user", sa.Boolean),
        sa.column("password_changed_at", sa.DateTime),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    now = utc_now()
    op.bulk_insert(
        users,
        [
            {
                "email": SEED_USER_EMAIL,
                "first_name": SEED_USER_FIRST_NAME,
                "last_name": SEED_USER_LAST_NAME,
                "password_hash": password_hash,
                "role": UserRole.ACCOUNT_ADMIN.value,
                "status": UserStatus.ACTIVE.value,
                "must_change_password": False,
                "is_seed_user": True,
                "password_changed_at": now,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )
    logger.info(
        "Seeded the default administrator %s (%s) from APP_ADMIN_PASSWORD",
        SEED_USER_EMAIL, UserRole.ACCOUNT_ADMIN.value,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_seed_user'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
