"""initial schema

Revision ID: db47416a408c
Revises: 
Create Date: 2026-09-16 16:20:01.217062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = 'db47416a408c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('exchange_id', sa.String(length=8), nullable=False),
    sa.Column('exchange_segment', sa.String(length=16), nullable=False),
    sa.Column('segment_code', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.String(length=16), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=32), nullable=False),
    sa.Column('underlying_scrip', sa.Integer(), nullable=True),
    sa.Column('trading_symbol', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('strike_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('option_type', sa.String(length=2), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index('ix_instruments_chain', ['underlying_symbol', 'expiry_date', 'strike_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_instrument_type'), ['instrument_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_security_id'), ['security_id'], unique=True)
        batch_op.create_index('ix_instruments_type_expiry', ['instrument_type', 'expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_underlying_symbol'), ['underlying_symbol'], unique=False)

    op.create_table('orders',
    sa.Column('client_order_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('trading_symbol', sa.String(length=128), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('strike_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('option_type', sa.String(length=2), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('average_fill_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('is_close_order', sa.Boolean(), nullable=False),
    sa.Column('placed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('last_event_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('completed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_client_order_id'), ['client_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_placed_at'), ['placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_security_id'), ['security_id'], unique=False)
        batch_op.create_index('ix_orders_security_placed', ['security_id', 'placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_side'), ['side'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index('ix_orders_status_placed', ['status', 'placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_strike_price'), ['strike_price'], unique=False)

    op.create_table('positions',
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('trading_symbol', sa.String(length=128), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('strike_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('option_type', sa.String(length=2), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('net_quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('total_charges', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('buy_quantity', sa.Integer(), nullable=False),
    sa.Column('sell_quantity', sa.Integer(), nullable=False),
    sa.Column('buy_value', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('sell_value', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('closed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_is_open'), ['is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_security_id'), ['security_id'], unique=False)
        batch_op.create_index('ix_positions_security_open', ['security_id', 'is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_strike_price'), ['strike_price'], unique=False)

    op.create_table('order_charges',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('turnover', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('brokerage', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('ctt', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('exchange_transaction_charge', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('sebi_turnover_fee', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('stamp_duty', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('gst', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('total_charges', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('rates_version', sa.String(length=32), nullable=True),
    sa.Column('breakdown_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_charges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_charges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_charges_order_id'), ['order_id'], unique=True)

    op.create_table('order_events',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('event_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_events_event_at'), ['event_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('order_fills',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fill_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('price', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('book_level', sa.Integer(), nullable=True),
    sa.Column('slippage_ticks', sa.Integer(), nullable=False),
    sa.Column('reference_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_fills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_fill_at'), ['fill_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_order_id'), ['order_id'], unique=False)

    op.create_table('trade_notes',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.String(length=32), nullable=True),
    sa.Column('trading_symbol', sa.String(length=128), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('noted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('edited_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_notes_noted_at'), ['noted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_notes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_notes_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_notes_security_id'), ['security_id'], unique=False)
        batch_op.create_index('ix_trade_notes_security_noted', ['security_id', 'noted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_notes_security_noted')
        batch_op.drop_index(batch_op.f('ix_trade_notes_security_id'))
        batch_op.drop_index(batch_op.f('ix_trade_notes_position_id'))
        batch_op.drop_index(batch_op.f('ix_trade_notes_order_id'))
        batch_op.drop_index(batch_op.f('ix_trade_notes_noted_at'))
        batch_op.drop_index(batch_op.f('ix_trade_notes_id'))
        batch_op.drop_index(batch_op.f('ix_trade_notes_created_at'))

    op.drop_table('trade_notes')
    with op.batch_alter_table('order_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_fills_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_fills_id'))
        batch_op.drop_index(batch_op.f('ix_order_fills_fill_at'))
        batch_op.drop_index(batch_op.f('ix_order_fills_created_at'))

    op.drop_table('order_fills')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_events_id'))
        batch_op.drop_index(batch_op.f('ix_order_events_event_at'))
        batch_op.drop_index(batch_op.f('ix_order_events_created_at'))

    op.drop_table('order_events')
    with op.batch_alter_table('order_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_charges_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_charges_id'))
        batch_op.drop_index(batch_op.f('ix_order_charges_created_at'))

    op.drop_table('order_charges')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_strike_price'))
        batch_op.drop_index('ix_positions_security_open')
        batch_op.drop_index(batch_op.f('ix_positions_security_id'))
        batch_op.drop_index(batch_op.f('ix_positions_is_open'))
        batch_op.drop_index(batch_op.f('ix_positions_id'))
        batch_op.drop_index(batch_op.f('ix_positions_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_positions_created_at'))

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_strike_price'))
        batch_op.drop_index('ix_orders_status_placed')
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_side'))
        batch_op.drop_index('ix_orders_security_placed')
        batch_op.drop_index(batch_op.f('ix_orders_security_id'))
        batch_op.drop_index(batch_op.f('ix_orders_placed_at'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_orders_client_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_underlying_symbol'))
        batch_op.drop_index('ix_instruments_type_expiry')
        batch_op.drop_index(batch_op.f('ix_instruments_security_id'))
        batch_op.drop_index(batch_op.f('ix_instruments_is_active'))
        batch_op.drop_index(batch_op.f('ix_instruments_instrument_type'))
        batch_op.drop_index(batch_op.f('ix_instruments_id'))
        batch_op.drop_index(batch_op.f('ix_instruments_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_instruments_created_at'))
        batch_op.drop_index('ix_instruments_chain')

    op.drop_table('instruments')
    # ### end Alembic commands ###
