"""Add the BTST overnight journal and its holdings

Three tables for the NSE BTST Overnight module. Its own, deliberately, rather
than columns bolted onto `swing_sessions`: that journal's shape is a
breadth-ramped rotation's record and this strategy has no breadth and no ramp,
while it wants things that one has no room for -- each candidate's volume ratio
against its own 20-day average, its close location within the day's range, and
afterwards the realised overnight gap. Bending it would also have put a
migration on a live, ARMED strategy.

`btst_holdings` is the one that is UPDATED rather than appended to. It holds
the open question "did the exit run", which is answered by changing it; the
append-only record of what happened is `btst_decisions`.

Additive only. Nothing existing is altered, so the rotation is untouched.

Revision ID: eeea383182b8
Revises: f2a8b1c94d37
Create Date: 2026-09-19 16:47:45.262026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = 'eeea383182b8'
down_revision: Union[str, None] = 'f2a8b1c94d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btst_sessions',
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('run_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('completed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('index_symbol', sa.String(length=32), nullable=True),
    sa.Column('index_close', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('index_sma', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('gate_on', sa.Boolean(), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=True),
    sa.Column('tradable_count', sa.Integer(), nullable=True),
    sa.Column('symbols_with_bars', sa.Integer(), nullable=True),
    sa.Column('symbols_with_quotes', sa.Integer(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('picked_count', sa.Integer(), nullable=True),
    sa.Column('filter_counts_json', sa.Text(), nullable=True),
    sa.Column('ranking_json', sa.Text(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('regime_enforced', sa.Boolean(), nullable=True),
    sa.Column('fno_excluded', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('btst_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_btst_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_id'), ['id'], unique=False)
        batch_op.create_index('ix_btst_sessions_lookup', ['strategy_key', 'session_date', 'run_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_run_kind'), ['run_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_sessions_strategy_key'), ['strategy_key'], unique=False)

    op.create_table('btst_decisions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('session_high', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('session_low', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('session_volume', sa.Integer(), nullable=True),
    sa.Column('vol_ratio', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('clv', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('breakout_high', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('momentum', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('sma', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('turnover_20d', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('regime_gate_on', sa.Boolean(), nullable=True),
    sa.Column('regime_enforced', sa.Boolean(), nullable=True),
    sa.Column('fno_excluded', sa.Boolean(), nullable=True),
    sa.Column('fno_eligible', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['btst_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('btst_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_btst_decisions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_decisions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_decisions_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_decisions_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_btst_decisions_session_symbol', ['session_id', 'symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_decisions_symbol'), ['symbol'], unique=False)

    op.create_table('btst_holdings',
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('entry_session_date', sa.Date(), nullable=False),
    sa.Column('entry_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=True),
    sa.Column('entry_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_gate_on', sa.Boolean(), nullable=True),
    sa.Column('entry_regime_enforced', sa.Boolean(), nullable=True),
    sa.Column('exit_status', sa.String(length=16), nullable=False),
    sa.Column('exit_order_id', sa.Integer(), nullable=True),
    sa.Column('exit_price', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('exited_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('exit_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=500), nullable=True),
    sa.Column('overnight_gap', src.database.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['entry_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['exit_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('btst_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_btst_holdings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_entry_session_date'), ['entry_session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_exit_status'), ['exit_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_id'), ['id'], unique=False)
        batch_op.create_index('ix_btst_holdings_open', ['strategy_key', 'portfolio_id', 'exit_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_strategy_key'), ['strategy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_btst_holdings_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('btst_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_btst_holdings_symbol'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_strategy_key'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_security_id'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_position_id'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_portfolio_id'))
        batch_op.drop_index('ix_btst_holdings_open')
        batch_op.drop_index(batch_op.f('ix_btst_holdings_id'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_exit_status'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_entry_session_date'))
        batch_op.drop_index(batch_op.f('ix_btst_holdings_created_at'))

    op.drop_table('btst_holdings')
    with op.batch_alter_table('btst_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_btst_decisions_symbol'))
        batch_op.drop_index('ix_btst_decisions_session_symbol')
        batch_op.drop_index(batch_op.f('ix_btst_decisions_session_id'))
        batch_op.drop_index(batch_op.f('ix_btst_decisions_security_id'))
        batch_op.drop_index(batch_op.f('ix_btst_decisions_order_id'))
        batch_op.drop_index(batch_op.f('ix_btst_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_btst_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_btst_decisions_action'))

    op.drop_table('btst_decisions')
    with op.batch_alter_table('btst_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_btst_sessions_strategy_key'))
        batch_op.drop_index(batch_op.f('ix_btst_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_btst_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_btst_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_btst_sessions_run_kind'))
        batch_op.drop_index(batch_op.f('ix_btst_sessions_portfolio_id'))
        batch_op.drop_index('ix_btst_sessions_lookup')
        batch_op.drop_index(batch_op.f('ix_btst_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_btst_sessions_created_at'))

    op.drop_table('btst_sessions')
    # ### end Alembic commands ###
