"""add portfolios and the cash ledger

Paper money stops being unlimited. A portfolio behaves like one demat account:
it holds money, it is attached to strategies, and every order, position and
chart trade belongs to exactly one of them.

Three things happen here, in this order, and the order matters:

1. The tables are created and `portfolio_id` is added NULLABLE to the three
   trade tables.
2. A default portfolio is created and every existing row is assigned to it,
   then its opening balance is deposited and **the trades already in the
   database are replayed into the ledger** -- a debit and its charges for each
   buy, a credit for each sell, at the timestamps they actually happened. Cash
   therefore reflects that the two open positions in this database were paid
   for. Realised P&L is untouched: this migration writes only cash entries.
3. Only then is `portfolio_id` made NOT NULL, because a trade belonging to no
   portfolio would vanish from every scoped view.

The opening balance is a deliberate configured number
(`portfolios.default_opening_balance`), not something derived from existing
P&L. If the replay would leave cash negative the migration says so loudly and
continues: silently inflating the opening deposit would be inventing money.

The position and chart-trade indexes change with the lookups they serve --
(portfolio_id, security_id, is_open) rather than (security_id, is_open) --
because without the portfolio in the key two portfolios holding the same strike
would net into one position row.

Revision ID: f613abaeee0f
Revises: 07984c863dd3
Create Date: 2026-09-18 01:37:28.627839

"""
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import src.database.base  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = 'f613abaeee0f'
down_revision: Union[str, None] = '07984c863dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEFAULT_PORTFOLIO_NAME = "Main"
DEFAULT_OPENING_BALANCE = Decimal("1000000")
TRADE_TABLES = ("orders", "positions", "chart_trades")


def _configured(key: str, fallback):
    """A config value, or the fallback if config is not loadable here."""
    try:
        from src import config_utils

        value = config_utils.get_property_value(key, None)
        return value if value not in (None, "") else fallback
    except Exception:  # noqa: BLE001 - a migration must not need the app config
        return fallback


def _strategy_keys() -> list:
    try:
        from src.strategies.services.strategy_registry import get_strategy_registry

        return [definition.key for definition in get_strategy_registry().all()]
    except Exception:  # noqa: BLE001
        return []


def upgrade() -> None:
    op.create_table('portfolios',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_portfolios_status'), ['status'], unique=False)

    op.create_table('portfolio_strategies',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'strategy_key', name='uq_portfolio_strategy')
    )
    with op.batch_alter_table('portfolio_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_strategies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_strategies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_strategies_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_strategies_strategy_key'), ['strategy_key'], unique=False)

    op.create_table('cash_ledger',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('amount', src.database.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('entry_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_ledger_entry_at'), ['entry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_ledger_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_ledger_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_cash_ledger_portfolio_at', ['portfolio_id', 'entry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_ledger_portfolio_id'), ['portfolio_id'], unique=False)

    # --- 1. nullable columns, so existing rows survive the ALTER ------------
    for table in TRADE_TABLES:
        op.add_column(table, sa.Column('portfolio_id', sa.Integer(), nullable=True))

    # --- 2. the default portfolio, the backfill and the ledger replay -------
    connection = op.get_bind()
    has_trades = any(
        int(
            connection.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar() or 0
        )
        > 0
        for table in TRADE_TABLES
    )

    name = str(_configured("portfolios.default_name", DEFAULT_PORTFOLIO_NAME))
    opening = Decimal(
        str(_configured("portfolios.default_opening_balance", DEFAULT_OPENING_BALANCE))
    )
    now = sa.func.current_timestamp()

    connection.execute(
        sa.text(
            "INSERT INTO portfolios (name, description, status, created_at, updated_at) "
            "VALUES (:name, :description, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        ).bindparams(
            name=name,
            description=(
                "Created when portfolios were introduced. Every trade that "
                "predates them belongs to it."
            ),
        )
    )
    portfolio_id = int(
        connection.execute(
            sa.text("SELECT id FROM portfolios WHERE name = :name").bindparams(name=name)
        ).scalar()
    )

    for key in _strategy_keys():
        connection.execute(
            sa.text(
                "INSERT INTO portfolio_strategies "
                "(portfolio_id, strategy_key, created_at, updated_at) "
                "VALUES (:portfolio_id, :key, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ).bindparams(portfolio_id=portfolio_id, key=key)
        )

    for table in TRADE_TABLES:
        connection.execute(
            sa.text(
                f"UPDATE {table} SET portfolio_id = :portfolio_id"
            ).bindparams(portfolio_id=portfolio_id)
        )

    # The opening deposit, backdated before every trade so the replayed
    # entries land on top of it rather than under it.
    first_trade_at = connection.execute(
        sa.text("SELECT MIN(placed_at) FROM orders")
    ).scalar()
    connection.execute(
        sa.text(
            "INSERT INTO cash_ledger "
            "(portfolio_id, entry_type, amount, note, entry_at, created_at, updated_at) "
            "VALUES (:portfolio_id, 'DEPOSIT', :amount, :note, "
            "COALESCE(:entry_at, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        ).bindparams(
            portfolio_id=portfolio_id,
            amount=float(opening),
            note="Opening balance",
            entry_at=first_trade_at,
        )
    )

    _replay_trades(connection, portfolio_id, opening)

    # --- 3. NOT NULL, now that nothing is unassigned ------------------------
    for table in TRADE_TABLES:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.alter_column(
                'portfolio_id', existing_type=sa.Integer(), nullable=False
            )

    with op.batch_alter_table('chart_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_trades_underlying_status')
        batch_op.create_index(batch_op.f('ix_chart_trades_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_chart_trades_portfolio_underlying_status', ['portfolio_id', 'underlying_security_id', 'status'], unique=False)
        batch_op.create_foreign_key(
            'fk_chart_trades_portfolio', 'portfolios', ['portfolio_id'], ['id']
        )

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_orders_portfolio_placed', ['portfolio_id', 'placed_at'], unique=False)
        batch_op.create_foreign_key(
            'fk_orders_portfolio', 'portfolios', ['portfolio_id'], ['id']
        )

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_security_open')
        batch_op.create_index(batch_op.f('ix_positions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_positions_portfolio_security_open', ['portfolio_id', 'security_id', 'is_open'], unique=False)
        batch_op.create_foreign_key(
            'fk_positions_portfolio', 'portfolios', ['portfolio_id'], ['id']
        )


def _replay_trades(connection, portfolio_id: int, opening: Decimal) -> None:
    """Write the cash entries the trades already in this database would have.

    A buy debits what it paid and its charges; a sell credits what it received
    and debits its charges. Charges are posted ONCE per order, from the stored
    total -- they were recomputed on cumulative executed quantity, not
    accumulated per fill, so posting them per fill would charge twice.
    """
    fills = connection.execute(
        sa.text(
            "SELECT f.order_id, f.price, f.quantity, f.fill_at, o.side, "
            "       o.trading_symbol, o.client_order_id "
            "FROM order_fills f JOIN orders o ON o.id = f.order_id "
            "ORDER BY f.fill_at ASC, f.id ASC"
        )
    ).fetchall()

    balance = opening
    for fill in fills:
        row = fill._mapping
        consideration = (
            Decimal(str(row["price"])) * Decimal(int(row["quantity"]))
        ).quantize(Decimal("0.01"))
        is_buy = str(row["side"]).upper() == "BUY"
        amount = -consideration if is_buy else consideration
        balance += amount
        connection.execute(
            sa.text(
                "INSERT INTO cash_ledger "
                "(portfolio_id, entry_type, amount, order_id, note, entry_at, "
                " created_at, updated_at) "
                "VALUES (:portfolio_id, :entry_type, :amount, :order_id, :note, "
                " :entry_at, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ).bindparams(
                portfolio_id=portfolio_id,
                entry_type="TRADE_DEBIT" if is_buy else "TRADE_CREDIT",
                amount=float(amount),
                order_id=int(row["order_id"]),
                note=f"{row['side']} {row['quantity']} of {row['trading_symbol']}",
                entry_at=row["fill_at"],
            )
        )

    charges = connection.execute(
        sa.text(
            "SELECT c.order_id, c.total_charges, o.client_order_id, "
            "       COALESCE(o.completed_at, o.last_event_at) AS charged_at "
            "FROM order_charges c JOIN orders o ON o.id = c.order_id "
            "ORDER BY c.order_id ASC"
        )
    ).fetchall()

    for charge in charges:
        row = charge._mapping
        total = Decimal(str(row["total_charges"] or 0)).quantize(Decimal("0.01"))
        if total == 0:
            continue
        balance -= total
        connection.execute(
            sa.text(
                "INSERT INTO cash_ledger "
                "(portfolio_id, entry_type, amount, order_id, note, entry_at, "
                " created_at, updated_at) "
                "VALUES (:portfolio_id, 'CHARGES', :amount, :order_id, :note, "
                " :entry_at, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ).bindparams(
                portfolio_id=portfolio_id,
                amount=float(-total),
                order_id=int(row["order_id"]),
                note=f"Charges on {row['client_order_id']}",
                entry_at=row["charged_at"],
            )
        )

    if balance < 0:
        # Loud, and NOT fixed by inflating the deposit: the opening balance is
        # a deliberate configured number, and quietly adding to it would be
        # inventing money to make a migration look tidy.
        print(
            f"WARNING: replaying existing trades leaves this portfolio at "
            f"{balance}, which is negative. The opening balance "
            f"(portfolios.default_opening_balance) is smaller than what the "
            f"trades already in this database spent. Deposit more on the "
            f"Portfolios page; no trade has been changed."
        )


def downgrade() -> None:
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_positions_portfolio', type_='foreignkey')
        batch_op.drop_index('ix_positions_portfolio_security_open')
        batch_op.drop_index(batch_op.f('ix_positions_portfolio_id'))
        batch_op.create_index('ix_positions_security_open', ['security_id', 'is_open'], unique=False)
        batch_op.drop_column('portfolio_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_portfolio', type_='foreignkey')
        batch_op.drop_index('ix_orders_portfolio_placed')
        batch_op.drop_index(batch_op.f('ix_orders_portfolio_id'))
        batch_op.drop_column('portfolio_id')

    with op.batch_alter_table('chart_trades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chart_trades_portfolio', type_='foreignkey')
        batch_op.drop_index('ix_chart_trades_portfolio_underlying_status')
        batch_op.drop_index(batch_op.f('ix_chart_trades_portfolio_id'))
        batch_op.create_index('ix_chart_trades_underlying_status', ['underlying_security_id', 'status'], unique=False)
        batch_op.drop_column('portfolio_id')

    with op.batch_alter_table('cash_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_ledger_portfolio_id'))
        batch_op.drop_index('ix_cash_ledger_portfolio_at')
        batch_op.drop_index(batch_op.f('ix_cash_ledger_order_id'))
        batch_op.drop_index(batch_op.f('ix_cash_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_cash_ledger_entry_type'))
        batch_op.drop_index(batch_op.f('ix_cash_ledger_entry_at'))
        batch_op.drop_index(batch_op.f('ix_cash_ledger_created_at'))

    op.drop_table('cash_ledger')
    with op.batch_alter_table('portfolio_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_strategies_strategy_key'))
        batch_op.drop_index(batch_op.f('ix_portfolio_strategies_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_strategies_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_strategies_created_at'))

    op.drop_table('portfolio_strategies')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_status'))
        batch_op.drop_index(batch_op.f('ix_portfolios_name'))
        batch_op.drop_index(batch_op.f('ix_portfolios_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_created_at'))

    op.drop_table('portfolios')
